I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story scripts/ch3.rpy", line 484, in script
    "We all stop walking. Suddenly in the forest to the left there is a figure where none was before."
IOError: Couldn't find file 'Guardian of the  Forest.ogg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story scripts/ch3.rpy", line 484, in script
    "We all stop walking. Suddenly in the forest to the left there is a figure where none was before."
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/ast.py", line 715, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/exports.py", line 1393, in say
    who(what, *args, **kwargs)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/character.py", line 1205, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/character.py", line 871, in do_display
    **display_args)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/character.py", line 621, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/display/core.py", line 3101, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/display/core.py", line 3794, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/audio/audio.py", line 1101, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/audio/audio.py", line 1079, in periodic_thread_main
    periodic_pass()
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/audio/audio.py", line 1021, in periodic_pass
    c.periodic()
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/audio/audio.py", line 487, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\vyana\OneDrive\Documents\renpy\renpy-7.4.4-sdk/renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'Guardian of the  Forest.ogg'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Song of Glass 1.0
Tue Oct 12 17:42:56 2021
